# Generated by Django 2.2 on 2019-04-23 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.Producto'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.TipoServicio'),
        ),
    ]
