# Generated by Django 2.2 on 2019-04-23 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0002_auto_20190423_0156'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='id_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Comuna'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Sexo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_tipo_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.TipoCargo'),
        ),
    ]
