# Generated by Django 2.2 on 2019-04-23 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odontologia', '0004_auto_20190421_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre :')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut :')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre :')),
                ('appaterno', models.CharField(max_length=50, verbose_name='Apellido Paterno :')),
                ('apmaterno', models.CharField(max_length=50, verbose_name='Apellido Materno :')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento :')),
                ('fono', models.IntegerField(verbose_name='Telefono :')),
                ('email', models.EmailField(max_length=254, verbose_name='Email :')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección :')),
                ('username', models.CharField(max_length=20, verbose_name='Usuario :')),
                ('password', models.CharField(max_length=20, verbose_name='Contraseña :')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Comuna')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre :')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha :')),
                ('hora', models.TimeField(verbose_name='Hora :')),
                ('id_servicio', models.CharField(max_length=100, verbose_name='Id Dentista :')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontologia.Dentista')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
            options={
                'verbose_name': 'Reservacion',
                'verbose_name_plural': 'Reservaciones',
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Sexo'),
        ),
    ]
