# Generated by Django 2.2 on 2019-04-23 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odontologia', '0004_auto_20190421_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre :')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción :')),
                ('unimed', models.IntegerField(verbose_name='Unidad de Medida :')),
                ('precos', models.IntegerField(verbose_name='Precio Costo :')),
                ('preven', models.IntegerField(verbose_name='Precio Venta :')),
                ('id_producto_servicio', models.CharField(max_length=50, verbose_name='Producto Servicio :')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado :')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha Atención :')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado :')),
                ('id_dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontologia.Dentista')),
            ],
            options={
                'verbose_name': 'Atencion',
                'verbose_name_plural': 'Atenciones',
            },
        ),
    ]
