# Generated by Django 2.2 on 2019-04-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0002_auto_20190420_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
