# Generated by Django 2.2 on 2019-04-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0003_dentista_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentista',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción :'),
        ),
    ]
